package com.example.webdemo.dao;

import org.apache.ibatis.annotations.Mapper;

import com.example.webdemo.beans.CreditFileRepay;
import com.example.webdemo.dao.mapper.CommonMapper;

@Mapper
public interface CreditFileRepayMapper extends CommonMapper<CreditFileRepay> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_file_repay
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    int insert(CreditFileRepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_file_repay
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    int insertSelective(CreditFileRepay record);
}