package com.example.webdemo.beans;

import java.math.BigDecimal;
import java.util.Date;

public class CreditFileRepay extends CreditFileRepayKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.channel_id
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.apply_id
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.repay_num
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private Integer repayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.repay_date
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private String repayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.repay_principal
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private BigDecimal repayPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.repay_interest
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private BigDecimal repayInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.repay_penalty_interest
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private BigDecimal repayPenaltyInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.repay_flag
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private String repayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.remarks
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.transfer_status
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private String transferStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.create_time
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_file_repay.update_time
     *
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.channel_id
     *
     * @return the value of credit_file_repay.channel_id
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.channel_id
     *
     * @param channelId the value for credit_file_repay.channel_id
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.apply_id
     *
     * @return the value of credit_file_repay.apply_id
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.apply_id
     *
     * @param applyId the value for credit_file_repay.apply_id
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.repay_num
     *
     * @return the value of credit_file_repay.repay_num
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public Integer getRepayNum() {
        return repayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.repay_num
     *
     * @param repayNum the value for credit_file_repay.repay_num
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRepayNum(Integer repayNum) {
        this.repayNum = repayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.repay_date
     *
     * @return the value of credit_file_repay.repay_date
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public String getRepayDate() {
        return repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.repay_date
     *
     * @param repayDate the value for credit_file_repay.repay_date
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRepayDate(String repayDate) {
        this.repayDate = repayDate == null ? null : repayDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.repay_principal
     *
     * @return the value of credit_file_repay.repay_principal
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public BigDecimal getRepayPrincipal() {
        return repayPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.repay_principal
     *
     * @param repayPrincipal the value for credit_file_repay.repay_principal
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRepayPrincipal(BigDecimal repayPrincipal) {
        this.repayPrincipal = repayPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.repay_interest
     *
     * @return the value of credit_file_repay.repay_interest
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public BigDecimal getRepayInterest() {
        return repayInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.repay_interest
     *
     * @param repayInterest the value for credit_file_repay.repay_interest
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRepayInterest(BigDecimal repayInterest) {
        this.repayInterest = repayInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.repay_penalty_interest
     *
     * @return the value of credit_file_repay.repay_penalty_interest
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public BigDecimal getRepayPenaltyInterest() {
        return repayPenaltyInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.repay_penalty_interest
     *
     * @param repayPenaltyInterest the value for credit_file_repay.repay_penalty_interest
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRepayPenaltyInterest(BigDecimal repayPenaltyInterest) {
        this.repayPenaltyInterest = repayPenaltyInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.repay_flag
     *
     * @return the value of credit_file_repay.repay_flag
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public String getRepayFlag() {
        return repayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.repay_flag
     *
     * @param repayFlag the value for credit_file_repay.repay_flag
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRepayFlag(String repayFlag) {
        this.repayFlag = repayFlag == null ? null : repayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.remarks
     *
     * @return the value of credit_file_repay.remarks
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.remarks
     *
     * @param remarks the value for credit_file_repay.remarks
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.transfer_status
     *
     * @return the value of credit_file_repay.transfer_status
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public String getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.transfer_status
     *
     * @param transferStatus the value for credit_file_repay.transfer_status
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setTransferStatus(String transferStatus) {
        this.transferStatus = transferStatus == null ? null : transferStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.create_time
     *
     * @return the value of credit_file_repay.create_time
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.create_time
     *
     * @param createTime the value for credit_file_repay.create_time
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_file_repay.update_time
     *
     * @return the value of credit_file_repay.update_time
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_file_repay.update_time
     *
     * @param updateTime the value for credit_file_repay.update_time
     * @mbggenerated Tue Oct 08 16:25:08 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}